name: activo_fijo
description: Aplicación para la gestión del activo fijo de la universidad.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^4.0.6
  http: ^0.13.4
  image: ^3.1.3
  crypto: ^3.0.2
  provider: ^6.0.2
  diacritic: ^0.1.3
  screenshot: ^1.2.3
  cool_alert: ^1.1.0
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  unique_identifier: ^0.2.2
  easy_signature_pad: ^1.0.6
  freezed_annotation: ^2.0.3
  flutter_easyloading: ^3.0.3
  font_awesome_flutter: ^10.1.0
  back_button_interceptor: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

